In [1]:
print('This is Vance Nygard\'s homework solution.')

This is Vance Nygard's homework solution.


In [2]:
import numpy as np

In [3]:
#Problem 1

vec = np.zeros(10)
vec[4] = 1
print(vec)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [4]:
# Problem 2
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#Problem 3

def reverse(x):
# Reverses a function, keeping the dimensions the same.
    z = np.array(x)
    length = len(x)
    y = [] 
    for i,value in enumerate(x):
        index = length - i - 1
        inv_value = z[index]
        y.append(inv_value)
    return y

m = np.arange(0,10)
reverse(m)
print(m)
print(reverse(m))

[0 1 2 3 4 5 6 7 8 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [6]:
#Problem 4

def find_nonzero(x):
    #Find the nonzero elements of an array.
    z = np.array(x)
    index = np.where(z == 0)
    return index
    print(index)
        
find_nonzero(np.array([1,2,0,0,4,0]))

(array([2, 3, 5], dtype=int64),)

In [7]:
#Problem 5

x = 1 * np.random.randn(3,3) + 0
x

array([[ 1.25658987, -0.40346472, -0.32069935],
       [ 0.04146541,  1.4523445 ,  0.88795065],
       [ 0.02083078, -1.21906165,  0.02759444]])

In [8]:
#Problem 6

x = np.random.rand(10,10)
y = x[:,1]
z = x[3,:]
print(x)
print(np.amin(y))
print(np.amin(z))

[[ 0.34841798  0.99311306  0.34209674  0.87663094  0.31052149  0.51779737
   0.25555441  0.76422167  0.41693567  0.05545422]
 [ 0.08315386  0.57197218  0.66166056  0.20138118  0.43888779  0.25699086
   0.53388779  0.19318932  0.31210414  0.73174991]
 [ 0.4584181   0.82358577  0.09948012  0.7749115   0.82229096  0.51650448
   0.20633936  0.30255494  0.51607441  0.06134086]
 [ 0.09860867  0.29188039  0.22587179  0.58103242  0.85560215  0.39918326
   0.11052305  0.00936605  0.53512746  0.90109795]
 [ 0.3437578   0.80705239  0.83603842  0.66430249  0.86850144  0.53939606
   0.51474829  0.49804981  0.56982374  0.56816905]
 [ 0.69825721  0.68478147  0.82312194  0.95166384  0.26357208  0.55549404
   0.63299263  0.33773771  0.37844569  0.78944279]
 [ 0.6614338   0.78523911  0.71346029  0.83953346  0.49884536  0.32335902
   0.83387568  0.09957428  0.71225574  0.59467295]
 [ 0.37989057  0.70018726  0.5496391   0.84485683  0.25662377  0.1520217
   0.6797243   0.59091707  0.23349458  0.22911187]
 

In [9]:
#Problem 7
vec = np.random.rand(10)
vec[2] == 0
for index, i in enumerate (vec):
    j = np.random.rand(1)
    if i == 0:
        vec[index] == j
print(vec)

[ 0.18359185  0.89752713  0.43135908  0.56420084  0.55404611  0.94538816
  0.58916582  0.81737692  0.88709495  0.96023577]


In [10]:
#Problem 8
vec = np.sort(np.random.rand(10))
vec

array([ 0.05296783,  0.20826288,  0.35775149,  0.36031513,  0.38230586,
        0.42982426,  0.45283109,  0.52416585,  0.59093241,  0.83803723])

In [11]:
#Problem 9

def is_equal(a,b):
    "Test for equality of arrays."

    if np.size(a) == np.size(b):
        if np.sum(a==b) == len(a):
            return True
    else:
        return False

s = np.arange(1,5)
t = np.arange(1,5)
u = np.arange(1,6)
v = np.random.rand(1,5)

print(is_equal(s,t))
print(is_equal(s,u))
print(is_equal(s,v))

True
False
False


In [12]:
# Problem 10
x = np.random.rand(3,3)
y = x.mean(axis=0).reshape(1,3)


print(x)
print(y)

a = np.zeros((3,3))
a[:,0] = x[:,0] - y[:,0]
a[:,1] = x[:,1] - y[:,1]
a[:,2] = x[:,2] - y[:,2]
# a = x - y
print()
print(a)

[[ 0.25262921  0.72999012  0.20735412]
 [ 0.3445809   0.62553697  0.39511613]
 [ 0.62538714  0.07265755  0.76128888]]
[[ 0.40753242  0.47606155  0.45458638]]

[[-0.15490321  0.25392857 -0.24723225]
 [-0.06295152  0.14947543 -0.05947025]
 [ 0.21785473 -0.403404    0.3067025 ]]


In [13]:
# Problem 11

x = np.random.rand(5,5,3)
y = np.random.rand(5,5)
print(x*y)

#Returns an error as expected. Continued in next cell.

ValueError: operands could not be broadcast together with shapes (5,5,3) (5,5) 

In [ ]:
#Problem 11

x = np.random.rand(3,5,5)
y = np.random.rand(5,5)
print(x*y)

In [ ]:
# Problem 12

z = np.arange(1,15)
a = np.zeros(4)
b = np.zeros(4)

for item in range(len(z)):
    if item + 4 > len(z):
        break
    else:
        a = z[item:item+4]
        b = np.vstack((b,a))
b = b[1:,:]
print(b)

In [ ]:
# Problem 13
import numpy as np

def cart2polar(xy):
    #   Return equivalent polar coordinates of specified cartesian points.
    #   Inputs: xy: array
    #              Nx2 array of Cartesian coordinates, with columns x and y respectively.
    #     Returns: rp: array
    #              Nx2 array of polar coordinates, with columns radius and angle (radians) respectively
    
    rp = np.zeros_like(xy)
    rp[:,0] = np.sqrt(xy[:,0]**2 + xy[:,1]**2)
    rp[:,1] = np.angle((xy[:,0] + xy[:,1]*1j))
    
    return rp
                   
cart2polar(np.array([[-4.,4.],[-4.,-4.]]))

In [44]:
#Problem 14
import time
t_start = time.time()

a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

t_end = time.time()

dte = t_end - t_start
dte 

0.0010001659393310547

In [45]:
#Problem 14, continued
import time
t_start = time.time()

sol = np.zeros_like(a)

for i in range(np.shape(a)[0]):
    for j in range(np.shape(a)[1]):
        for k in range(np.shape(a)[2]):
            for l in range(np.shape(a)[3]):
                sol[i,j,k,l] = a[i,j,k,l]*b[i,j,k,l]
t_end = time.time()

dtl = t_end - t_start
dtl

0.004000425338745117

In [47]:
#Problem 14, continued
# dte is the time taken to do the calulation element by element.
# dtl is the time taken to do the calculation with nested loops.
# dtr is the ratio of dte over dtl.
# This ratio means that element by element multiplication is 4x faster than done with loops.
# Might my computer have a quadcore processor?
dtr = dte/dtl
dtr

0.250014899576852

In [53]:
#Problem 15
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = np.copy(a[:2, :])  # A copy was made that has its own memory, and changing it won't change array(a).
    aa /= 4.
    a[:2, :] -= aa

    return a*b[:,np.newaxis]  # Array(b) needs a new dimension so that it can be broadcast with array(a).
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

In [42]:
#Problem 16

data = np.loadtxt('../python4geosciences/data/burl1h2010.txt', comments='#')

direction = data[:,5]
direction.dtype = 'float64'
speed = data[:,6]
speed.dtype = 'float64'
# print(np.shape(direction))

def vectorize(vdir, vspd):
    # vspd is direction; vspd is speed. This function vectorizes components.
    
    u = np.cos(vdir * np.pi / 180) * vspd
    v = np.sin(vdir * np.pi / 180) * vspd
    
    return(u, v)

u,v = vectorize(direction, speed)
print(u)
print()
print()
print(v)
    

[ -2.08397511  -1.96070053  -2.12119911 ...,  -9.56084447 -10.50707636
  -8.83345912]


[ 2.1580194   3.01921404  2.52794666 ...,  6.208885    5.5867116   5.1       ]


In [77]:
#Problem 17
class dataclass(object):
    def __init__(self,filename):
        f = open(filename)
        switch = 0
        self.temp = []
        self.salt = []
        
        for line in f.readlines():
            if switch == 1: 
                self.temp.append(line.split()[2])
                self.salt.append(line.split()[5])
            if line.split()[0] == '*END*': switch = 1
        
        self.temp = np.asarray(self.temp, dtype = 'float64')
        self.salt = np.asarray(self.salt, dtype = 'float64')
    
    def temp_max(self):
        return np.max(self.temp)
        
        
    def salt_mean(self):
        return np.mean(self.salt)

In [78]:
#Problem 17 continued

import glob
file_group = glob.glob('python4geosciences/data/MCH/*.cnv2')
wind = []
for filename in file_group:
    wind.append(dataclass(filename))

In [81]:
#Problem 18
#    Return the running average of a vector, with averaging window of size N.
    
#     Inputs:
#         vec: Input vector
#         N (int): Averaging window size, or number of elements to include in mean on either side of each element.
    
#     Outputs:
#         out: Vector of running-averaged values; same size as vec

def running_mean(array, N):
    array = np.asarray(array, dtype='float64')
    out = np.copy(array)
    for index in range(N,len(array)-N):
        out[index] = np.mean(array[index-N:index+N+1])
        
    return out[N:len(array)-N]