In [1]:
print('This is Vance Nygard\'s homework solution.')

This is Vance Nygard's homework solution.


In [2]:
import numpy as np

In [27]:
#Problem 1

vec = np.zeros(10)
vec[4] = 1
print(vec)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [28]:
# Problem 2
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [29]:
#Problem 3

def reverse(x):
# Reverses a function, keeping the dimensions the same.
    z = np.array(x)
    length = len(x)
    y = [] 
    for i,value in enumerate(x):
        index = length - i - 1
        inv_value = z[index]
        y.append(inv_value)
    return y

m = np.arange(0,10)
reverse(m)
print(m)
print(reverse(m))

[0 1 2 3 4 5 6 7 8 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [30]:
#Problem 4

def find_nonzero(x):
    #Find the nonzero elements of an array.
    z = np.array(x)
    index = np.where(z == 0)
    return index
    print(index)
        
find_nonzero(np.array([1,2,0,0,4,0]))

(array([2, 3, 5], dtype=int64),)

In [31]:
#Problem 5

x = 1 * np.random.randn(3,3) + 0
x

array([[-1.62108902, -0.29827366,  0.10183326],
       [-1.64241258,  1.64326746, -1.33609194],
       [-0.51684755, -1.63253471, -1.01440902]])

In [32]:
#Problem 6

x = np.random.rand(10,10)
y = x[:,1]
z = x[3,:]
print(x)
print(np.amin(y))
print(np.amin(z))

[[ 0.37391072  0.92923879  0.72973592  0.76466673  0.91361845  0.66311913
   0.63992471  0.47413649  0.01375875  0.08303508]
 [ 0.44371268  0.08306698  0.92307108  0.92677922  0.82549289  0.38732032
   0.3716443   0.93734481  0.26334899  0.54308844]
 [ 0.93599716  0.49082457  0.5441614   0.38231465  0.84589515  0.53929395
   0.65556634  0.87185649  0.6649714   0.78891471]
 [ 0.77591539  0.53526512  0.07201195  0.1622134   0.70032156  0.24351477
   0.7148782   0.89263884  0.22850564  0.53959574]
 [ 0.14384119  0.84196485  0.44536896  0.7307399   0.9713967   0.73850873
   0.125127    0.13659912  0.39695225  0.78965667]
 [ 0.36747929  0.27805708  0.02933034  0.88137037  0.25995491  0.41597687
   0.85974529  0.79580416  0.01976563  0.53541764]
 [ 0.7491136   0.57486293  0.35123461  0.09333313  0.73503117  0.34944217
   0.14239943  0.73268617  0.77100705  0.33062728]
 [ 0.09920387  0.03192472  0.96003961  0.74651012  0.03525686  0.85700854
   0.00125523  0.49957188  0.51595054  0.67850092]


In [33]:
#Problem 7
vec = np.random.rand(10)
vec[2] == 0
for index, i in enumerate (vec):
    j = np.random.rand(1)
    if i == 0:
        vec[index] == j
print(vec)

[ 0.12742852  0.05392379  0.02401282  0.64148816  0.81013039  0.26483162
  0.82270195  0.73790597  0.96226581  0.31962028]


In [34]:
#Problem 8
vec = np.sort(np.random.rand(10))
vec

array([ 0.03400166,  0.18975295,  0.22519392,  0.30010381,  0.421286  ,
        0.67197252,  0.67437538,  0.67760967,  0.94968923,  0.98825318])

In [35]:
#Problem 9

def is_equal(a,b):
    "Test for equality of arrays."

    if np.size(a) == np.size(b):
        if np.sum(a==b) == len(a):
            return True
    else:
        return False

s = np.arange(1,5)
t = np.arange(1,5)
u = np.arange(1,6)
v = np.random.rand(1,5)

print(is_equal(s,t))
print(is_equal(s,u))
print(is_equal(s,v))

True
False
False


In [36]:
# Problem 10
x = np.random.rand(3,3)
y = x.mean(axis=0).reshape(1,3)


print(x)
print(y)

a = np.zeros((3,3))
a[:,0] = x[:,0] - y[:,0]
a[:,1] = x[:,1] - y[:,1]
a[:,2] = x[:,2] - y[:,2]
# a = x - y
print()
print(a)

[[ 0.45398207  0.80490027  0.60294672]
 [ 0.79561607  0.5059969   0.16811047]
 [ 0.45896215  0.78444282  0.03625694]]
[[ 0.56952009  0.69844666  0.26910471]]

[[-0.11553802  0.10645361  0.33384201]
 [ 0.22609597 -0.19244976 -0.10099424]
 [-0.11055795  0.08599615 -0.23284777]]


In [37]:
# Problem 11

x = np.random.rand(5,5,3)
y = np.random.rand(5,5)
print(x*y)

#Returns an error as expected. Continued in next cell.

ValueError: operands could not be broadcast together with shapes (5,5,3) (5,5) 

In [38]:
#Problem 11

x = np.random.rand(3,5,5)
y = np.random.rand(5,5)
print(x*y)

[[[ 0.10549302  0.10513833  0.17665961  0.10296679  0.112134  ]
  [ 0.2524754   0.02219194  0.34266553  0.09510513  0.01115249]
  [ 0.04404914  0.03357736  0.06021436  0.18706498  0.33674533]
  [ 0.19086009  0.10752273  0.13071003  0.01983718  0.0315411 ]
  [ 0.39665235  0.00500729  0.43348452  0.1595635   0.61115209]]

 [[ 0.0122183   0.22229231  0.19770057  0.11856625  0.18559485]
  [ 0.29534917  0.09885937  0.00613135  0.06705121  0.01323717]
  [ 0.54902491  0.01693867  0.31363869  0.23737189  0.41007788]
  [ 0.19942552  0.06189906  0.24325053  0.36915055  0.16190203]
  [ 0.16816974  0.01934054  0.52348725  0.04545958  0.74160526]]

 [[ 0.21909759  0.02355034  0.0623901   0.13963388  0.2627551 ]
  [ 0.25355742  0.0468006   0.26275583  0.13502635  0.00800877]
  [ 0.27103439  0.01777396  0.1360978   0.0592055   0.44214087]
  [ 0.14722166  0.3392268   0.01677632  0.42016126  0.07658466]
  [ 0.01899909  0.01872659  0.64573488  0.21534356  0.75330342]]]


In [39]:
# Problem 12

z = np.arange(1,15)
a = np.zeros(4)
b = np.zeros(4)

for item in range(len(z)):
    if item + 4 > len(z):
        break
    else:
        a = z[item:item+4]
        b = np.vstack((b,a))
b = b[1:,:]
print(b)

[[  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [  5.   6.   7.   8.]
 [  6.   7.   8.   9.]
 [  7.   8.   9.  10.]
 [  8.   9.  10.  11.]
 [  9.  10.  11.  12.]
 [ 10.  11.  12.  13.]
 [ 11.  12.  13.  14.]]


In [40]:
# Problem 13
import numpy as np

def cart2polar(xy):
    #   Return equivalent polar coordinates of specified cartesian points.
    #   Inputs: xy: array
    #              Nx2 array of Cartesian coordinates, with columns x and y respectively.
    #     Returns: rp: array
    #              Nx2 array of polar coordinates, with columns radius and angle (radians) respectively
    
    rp = np.zeros_like(xy)
    rp[:,0] = np.sqrt(xy[:,0]**2 + xy[:,1]**2)
    rp[:,1] = np.angle((xy[:,0] + xy[:,1]*1j))
    
    return rp
                   
cart2polar(np.array([[-4.,4.],[-4.,-4.]]))

array([[ 5.65685425,  2.35619449],
       [ 5.65685425, -2.35619449]])

In [3]:
#Problem 14
import time
t_start = time.time()

a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

t_end = time.time()

dte = t_end - t_start
dte

0.026000022888183594

In [4]:
#Problem 14, continued
import time
t_start = time.time()

sol2 = np.zeros_like(a)

for i in range(np.shape(a)[0]):
    for j in range(np.shape(a)[1]):
        for k in range(np.shape(a)[2]):
            for l in range(np.shape(a)[3]):
                s = a[i,j,k,l]*b[i,j,k,l]
                sol2[i,j,k,l] = s
t_end = time.time()

print(np.all(sol==sol2))

dtl = t_end - t_start
dtl

True


0.005000114440917969

In [5]:
#Problem 14, continued
# dte is the time taken to do the calulation element by element.
# dtl is the time taken to do the calculation with nested loops.
# dtr is the ratio of dte over dtl.
# This ratio means that element by element multiplication is ~4x faster than done with loops.
# Might my computer have a quadcore processor?
dtr = dte/dtl
dtr

5.199885561701316

In [44]:
#Problem 15
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = np.copy(a[:2, :])  # A copy was made that has its own memory, and changing it won't change array(a).
    aa /= 4.
    a[:2, :] -= aa

    return a*b[:,np.newaxis]  # Array(b) needs a new dimension so that it can be broadcast with array(a).
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

In [45]:
#Problem 16

data = np.loadtxt('../python4geosciences/data/burl1h2010.txt', comments='#')

direction = data[:,5]
direction.dtype = 'float64'
speed = data[:,6]
speed.dtype = 'float64'
# print(np.shape(direction))

def vectorize(vdir, vspd):
    # vspd is direction; vspd is speed. This function vectorizes components.
    
    u = np.cos(vdir * np.pi / 180) * vspd
    v = np.sin(vdir * np.pi / 180) * vspd
    
    return(u, v)

u,v = vectorize(direction, speed)
print(u)
print()
print()
print(v)
    

[ -2.08397511  -1.96070053  -2.12119911 ...,  -9.56084447 -10.50707636
  -8.83345912]


[ 2.1580194   3.01921404  2.52794666 ...,  6.208885    5.5867116   5.1       ]


In [49]:
#Problem 17
class dataclass(object):
    def __init__(self,filename):
        f = open(filename)
        switch = 0
        self.temp = []
        self.salt = []
        
        for line in f.readlines():
            if switch == 1: 
                self.temp.append(line.split()[2])
                self.salt.append(line.split()[5])
            if line.split()[0] == '*END*': switch = 1
        
        self.temp = np.asarray(self.temp, dtype = 'float64')
        self.salt = np.asarray(self.salt, dtype = 'float64')
    
    def temp_max(self):
        return np.max(self.temp)
        
        
    def salt_mean(self):
        return np.mean(self.salt)

In [53]:
#Problem 17 continued

import glob
file_group = glob.glob('python4geosciences/data/MCH/*.cnv2')
wind = []
for filename in file_group:
    wind.append(dataclass(filename))

In [55]:
wind[1].salt()

IndexError: list index out of range

In [48]:
#Problem 18
#    Return the running average of a vector, with averaging window of size N.
    
#     Inputs:
#         vec: Input vector
#         N (int): Averaging window size, or number of elements to include in mean on either side of each element.
    
#     Outputs:
#         out: Vector of running-averaged values; same size as vec

def running_mean(array, N):
    array = np.asarray(array, dtype='float64')
    out = np.copy(array)
    for index in range(N,len(array)-N):
        out[index] = np.mean(array[index-N:index+N+1])
        
    return out[N:len(array)-N]